/** Step 1–4 SOAP wizard + right panel — Korean / English (APTA-style) */
export type SoapLocale = "ko" | "en";

const COPY = {
  ko: {
    step1Subtitle:
      "입력된 임상 논리를 분석하여 치명적인 Medical Red Flag를 스크리닝합니다.",
    chiefSection: "1. 주요 호소 증상 (Chief complaint)",
    chiefPlaceholderShort: "가장 불편한 부위와 증상을 간략히 적어주세요.",
    onsetSection: "2. 발병 시기 및 경위 (Onset & mechanism)",
    painSection: "3. 통증 양상 및 강도 (Pain pattern & intensity)",
    vasLabelPrefix: "통증 강도 (VAS)",
    aggravatingRelievingSection: "4. 통증 가중 및 완화 요인 (Aggravating & relieving)",
    aggravatingLong: "가중 요인 (어떨 때 아픈가요?)",
    relievingLong: "완화 요인 (어떨 때 편안한가요?)",
    screeningSectionTitle: "5. 부위별 특이 문진 (Region-specific screening)",
    groupSpine: "Spine 그룹",
    groupJoint: "Joint 그룹",
    patientDobMissing: "생년월일 미등록",
    outputLangLabel: "출력 언어",
    langOptKo: "한국어 (+ 영문 의학용어)",
    langOptEn: "English (100% Medical English)",
    langOptJa: "日本語",
    langOptVi: "Tiếng Việt",
    langOptTh: "ภาษาไทย",
    redFlagSectionTitle: "6. 전신 Red Flag (Night pain / Weight loss / Neurogenic bowel·bladder)",
    safetyTitle: "Re:PhyT Safety Net",
    safetySubtitle: "Medical Screening & Red Flag Detection",
    stepExamTitle: "환자 검사 데이터",
    stepEvalTitle: "임상 평가 및 진단",
    stepGoalTitle: "예후 및 치료 목표",
    stepPlanTitle: "중재 전략 설정",
    linkPatient: "환자 연결",
    selectPatient: "환자를 선택하세요",
    loadingPatients: "환자 목록 불러오는 중…",
    bodyRegion: "진단 부위",
    selectRegion: "부위 선택",
    visitTime: "진료/처치 일시 (수동 선택)",
    outputLanguage: "출력 언어",
    historyTaking: "병력 청취 (History taking)",
    chiefComplaint: "주호소 (Chief complaint)",
    chiefPlaceholder: "예: 우측 어깨 통증 2주, 오버헤드 시 악화",
    onset: "발병 (Onset)",
    traumaType: "외상 여부",
    vas: "통증 (VAS)",
    painQuality: "통증 양상 (Pain quality)",
    aggravating: "가중 요인",
    aggravatingPh: "예: 오버헤드 동작, 장시간 앉기",
    relieving: "완화 요인",
    relievingPh: "예: 휴식, 온찜질",
    redFlagScreening: "Red Flag 스크리닝 (전신)",
    regionScreening: "부위 특이 스크리닝",
    selectRegionFirst: "먼저 Step 1에서 진단 부위를 선택해 주세요.",
    romMmtTitle: "관절별 정밀 평가 (ROM & MMT)",
    addMovement: "+ 측정 부위 추가",
    movementPlaceholder: "관절·동작 (예: Shoulder Flexion)",
    arom: "AROM [°]",
    prom: "PROM [°]",
    endFeel: "End-feel / 통증 패턴",
    mmt: "MMT",
    tbcTitle: "JOSPT 치료 기반 분류 (TBC) 선택",
    tbcHint: "환자의 핵심 기능적 결함을 선택하세요. AI가 최적의 중재 가이드라인을 매핑합니다.",
    tbcTooltipTitle: "JOSPT 진단 기준 (Inclusion)",
    outcomeTitle: "기능 평가 척도 (Outcome measures) 점수 입력",
    outcomeHint: "입력하신 객관적 점수는 AI의 치료 예후(Prognosis) 예측에 활용됩니다.",
    startMeasure: "척도 평가 시작",
    manualEntry: "직접 입력",
    manualNamePh: "척도명 (예: SPADI)",
    manualScorePh: "점수",
    manualMaxPh: "만점 (선택)",
    icfTitle: "ICF 기반 기능적 결함 선택",
    icfBody: "신체기능 및 구조 (Impairment)",
    icfActivity: "활동 제한 (Activity limitation)",
    icfParticipation: "참여 제약 (Participation restriction)",
    specialTestsTitle: "Evidence-Based 특수 검사 (Special tests)",
    specialTestsHint: "부위별 권장 검사 목록입니다. 양성/음성을 선택하면 평가란에 자동 반영됩니다.",
    notTested: "미실시",
    prognosisDuration: "예상 치료 기간 (Prognosis)",
    selectDuration: "치료 기간 선택",
    rehabPotential: "재활 잠재력 (Rehab potential)",
    stg: "단기 목표 (STG)",
    ltg: "장기 목표 (LTG)",
    stgPh: "2–4주 내 달성할 구체적이고 측정 가능한 목표를 입력하세요.",
    ltgPh: "6–12주 이상 장기 기능 회복 및 복귀 목표를 입력하세요.",
    step4Lead: "Step 4 APTA 4-Category Intervention System",
    manualTherapy: "1. 도수/수기 치료 (Manual therapy)",
    exercise: "2. 치료적 운동 (Therapeutic exercise)",
    modalities: "3. 기기 및 물리치료 (Modalities)",
    education: "4. 환자 교육 및 홈 프로그램 (Education & HEP)",
    interventionSummary: "AI 입력용 자동 요약 (Intervention)",
    add: "+ 추가",
    interventionNamePh: "중재명",
    minutesPh: "적용 시간(분)",
    exerciseNamePh: "운동명",
    holdPh: "Hold (초)",
    modalityTargetPh: "적용 부위",
    educationPh: "자세 교정, 금기 동작, 자가 운동, 복약/생활 지도 내용을 상세 기록하세요.",
    clinicalPlaceholder: "임상적 근거를 바탕으로 상세 내용을 입력하세요...",
    analyze: "🚀 AI 임상 스크리닝 리포트 생성",
    analyzing: "Scanning for Red Flags...",
    referralRequired: "의학적 감별 필요 상태",
    assessmentStatus: "평가 상태",
    referralPriority: "평가 중단 (Referral Priority)",
    differentialTitle: "감별 진단 근거 (Clinical reasoning)",
    actionTitle: "즉각적 행동 지침 (Action required)",
    actionDefault: "물리치료를 보류하고 관련 진료과 의뢰를 우선 진행하세요.",
    dismissCase: "의뢰 완료 및 새 케이스 스크리닝",
    noRedFlagTitle: "치명적인 위험 징후(Red Flag) 미발견",
    noRedFlagBody: "입력하신 데이터에서 치명적인 임상적 위험 징후는 발견되지 않았습니다.",
    verifyAgain: "새로 검증하기",
    feedbackAccurate: "판정 정확",
    feedbackFp: "오탐",
    feedbackFn: "미탐",
    notProvided: "미기재",
    none: "없음",
    prefixChief: "주소증",
    prefixOnset: "발병",
    prefixVas: "통증 (VAS)",
    prefixQuality: "통증 양상",
    prefixAgg: "가중 요인",
    prefixRelief: "완화 요인",
    prefixRedFlag: "Red Flag",
    prefixNotes: "기타 메모",
    redFlagNone: "특이사항 없음",
    tagTbc: "[TBC 분류]",
    tagOutcome: "[평가 척도]",
    tagIcfBf: "[ICF - 신체손상]",
    tagIcfAct: "[ICF - 활동제한]",
    tagIcfPart: "[ICF - 참여제약]",
    icfCatBody: "신체손상",
    icfCatActivity: "활동제한",
    icfCatParticipation: "참여제약",
    weeks: "주",
    analyzeError: "Red Flag 분석 중 오류가 발생했습니다.",
    tryAgain: "잠시 후 다시 시도해 주세요.",
    dbLogWarn: "분석은 완료되었으나 기록 저장에 실패했습니다(DB).",
    tagEstimatedDuration: "[예상 치료 기간]",
    tagRomMmt: "[ROM/MMT]",
    manualSummaryNone: "- 없음",
    interventionMin: "분",
    interventionSec: "초",
    modalityTargetLabel: "적용 부위:",
    tagBaselineVas: "[기초 데이터] VAS",
    tagDiagnosisRegion: "[기초 데이터] 진단 부위",
    notSelected: "미선택",
    tagIcfActivityLine: "[ICF - 활동제한]",
    tagOutcomeLine: "[평가 척도]",
    noData: "데이터 없음",
    loadVas: "VAS 불러오기",
    loadIcfActivity: "ICF 활동제한 불러오기",
    loadOutcome: "Outcome 점수 불러오기",
    loadRegion: "진단 부위 불러오기",
    loadIcfParticipation: "ICF 참여제약 불러오기",
    loadPrognosis: "예후 정보 불러오기",
    modalBadge: "Step 2 · 클릭형 기능 평가",
    modalTitleFallback: "기능 평가 척도",
    modalClose: "닫기",
    modalError: "클릭형 척도를 불러올 수 없습니다.",
    modalErrorHint:
      "진단 부위를 경추(neck) · 어깨(shoulder) · 요추(lumbar) · 무릎(knee) 등으로 선택해 주세요.",
    modalPreview: "실시간 결과",
    modalSelectPrompt: "문항을 선택해 주세요.",
    modalCancel: "취소",
    modalApply: "평가 완료 및 결과 반영",
    modalProgress: "진행",
    modalItems: "문항",
    scorePts: "점",
    womacPain: "통증",
    womacStiff: "강직",
    womacFunc: "일상 기능",
    womacSumLabel: "통증·강직·기능 합산",
    dashReferralFallback: "의학적 의뢰 필요",
    dashOverallScore: "종합 임상 논리 점수",
    dashLogicAudit: "임상 추론 사슬 검증",
    dashCpgCompliance: "CPG 가이드라인 준수율",
    dashAuditDefense: "삭감 방어력 (심사 대비)",
    dashTrajectory: "회복 궤적 예측",
    dashDefenseScore: "방어력 점수",
    dashWeeksLabel: "주 예상",
    dashRedFlagNote: "Red Flag 상태에서는 예측 해석보다 의학적 의뢰를 우선하세요.",
    dashRedFlagTitle: "Red Flag (치명적 위험 신호)",
    dashRedFlagBody: "입력된 데이터에서 치명적 의학적 위험 가능성이 감지되었습니다. 의학적 감별 및 의뢰를 우선 검토하세요.",
    dashRedFlagBodyClear: "치명적 Red Flag는 현재 감지되지 않았습니다.",
    dashYellowFlagTitle: "Yellow Flag (심리사회적 및 만성화 위험 요인)",
    dashYellowFlagBody: "입력된 데이터에서 확인된 심리사회적 주의 요인이 표시됩니다.",
    dashSaveRecord: "진단 기록 및 타임라인 저장하기",
    dashSaveRecordSaving: "저장 중...",
    dashSaveRecordSaved: "기록이 임상 타임라인에 안전하게 저장되었습니다.",
    dashSaveRecordAlready: "이미 최신 진단 기록이 저장되어 있습니다.",
    dashSaveRecordRetry: "저장 재시도",
    dashSaveRecordError: "저장 중 오류가 발생했습니다.",
    dashInterventionStrategyTitle: "중재 전략 심층 분석 (Intervention Strategy)",
    dashProfessionalDiscussionTitle: "임상 전문가 고찰 (Professional Discussion)",
    dashClinicalReasoningTitle: "임상 추론 및 생체역학적 원인 (Clinical Reasoning & Pathomechanics)",
    dashCommunity: "커뮤니티 및 SNS 공유",
    dashChallenge: "🏆 챌린지 참여",
    dashDefenseShare: "🛡️ 삭감 방어 팁 공유",
    dashInstagram: "📱 인스타 브랜딩",
    dashDisclaimer:
      "본 리포트는 입력된 데이터를 기반으로 학술적 가이드라인을 매핑한 AI 보조 도구입니다. 진단 및 치료의 최종 결정은 반드시 면허를 보유한 의료 전문가의 판단하에 이루어져야 하며, 본 서비스는 결과에 대해 법적 책임을 지지 않습니다.",
    dashWaiting: "AI 분석 대기 중입니다. 좌측 폼 입력 후 분석을 요청해 주세요.",
    dashImprovement: "개선 팁",
    shareFail: "공유 실패",
    shareChallengeOk: "🏆 챌린지 참여 카드가 커뮤니티에 업로드되었습니다.",
    shareDefenseOk: "🛡️ 삭감 방어 팁이 익명 공유되었습니다.",
    shareError: "커뮤니티 업로드 중 오류가 발생했습니다.",
  },
  en: {
    step1Subtitle:
      "Clinical logic is analyzed to screen for critical medical red flags.",
    chiefSection: "1. Chief complaint",
    chiefPlaceholderShort: "Briefly describe the primary symptom and location.",
    onsetSection: "2. Onset & mechanism",
    painSection: "3. Pain pattern & intensity",
    vasLabelPrefix: "Pain (VAS)",
    aggravatingRelievingSection: "4. Aggravating & relieving factors",
    aggravatingLong: "Aggravating factors (what worsens pain?)",
    relievingLong: "Relieving factors (what eases pain?)",
    screeningSectionTitle: "5. Region-specific screening",
    groupSpine: "Spine cluster",
    groupJoint: "Peripheral joint cluster",
    patientDobMissing: "DOB not on file",
    outputLangLabel: "Output language",
    langOptKo: "Korean + English medical terms",
    langOptEn: "English (Medical English)",
    langOptJa: "Japanese",
    langOptVi: "Vietnamese",
    langOptTh: "Thai",
    redFlagSectionTitle: "6. Systemic red flags (night pain / weight loss / neurogenic bowel or bladder)",
    safetyTitle: "Re:PhyT Safety Net",
    safetySubtitle: "Medical screening & red flag detection",
    stepExamTitle: "Patient examination data",
    stepEvalTitle: "Clinical evaluation & diagnosis",
    stepGoalTitle: "Prognosis & goals",
    stepPlanTitle: "Intervention planning",
    linkPatient: "Link patient",
    selectPatient: "Select a patient",
    loadingPatients: "Loading patients…",
    bodyRegion: "Body region",
    selectRegion: "Select region",
    visitTime: "Visit / treatment time (manual)",
    outputLanguage: "Output language",
    historyTaking: "History taking",
    chiefComplaint: "Chief complaint",
    chiefPlaceholder: "e.g., Right shoulder pain 2 weeks, worse with overhead activity",
    onset: "Onset",
    traumaType: "Mechanism",
    vas: "Pain (VAS)",
    painQuality: "Pain quality",
    aggravating: "Aggravating factors",
    aggravatingPh: "e.g., overhead tasks, prolonged sitting",
    relieving: "Relieving factors",
    relievingPh: "e.g., rest, heat",
    redFlagScreening: "Red flag screening (systemic)",
    regionScreening: "Region-specific screening",
    selectRegionFirst: "Select a body region in Step 1 first.",
    romMmtTitle: "Joint-level ROM & MMT",
    addMovement: "+ Add movement",
    movementPlaceholder: "Joint / movement (e.g., shoulder flexion)",
    arom: "AROM [°]",
    prom: "PROM [°]",
    endFeel: "End-feel / pain pattern",
    mmt: "MMT",
    tbcTitle: "JOSPT treatment-based classification (TBC)",
    tbcHint: "Select the primary impairment pattern. AI maps evidence-based care.",
    tbcTooltipTitle: "JOSPT inclusion criteria",
    outcomeTitle: "Outcome measures — score entry",
    outcomeHint: "Objective scores inform prognosis prediction.",
    startMeasure: "Start outcome measure",
    manualEntry: "Manual entry",
    manualNamePh: "Measure name (e.g., SPADI)",
    manualScorePh: "Score",
    manualMaxPh: "Max (optional)",
    icfTitle: "ICF — functional limitations",
    icfBody: "Body functions & structures (Impairment)",
    icfActivity: "Activity limitations",
    icfParticipation: "Participation restrictions",
    specialTestsTitle: "Evidence-based special tests",
    specialTestsHint: "Select positive/negative; findings sync to the evaluation field.",
    notTested: "Not tested",
    prognosisDuration: "Estimated duration of care",
    selectDuration: "Select duration",
    rehabPotential: "Rehab potential",
    stg: "Short-term goals (STG)",
    ltg: "Long-term goals (LTG)",
    stgPh: "Enter measurable goals for the next 2–4 weeks.",
    ltgPh: "Enter long-term functional return goals (6–12+ weeks).",
    step4Lead: "Step 4 — APTA four-category intervention system",
    manualTherapy: "1. Manual therapy",
    exercise: "2. Therapeutic exercise",
    modalities: "3. Physical agents / modalities",
    education: "4. Patient education & HEP",
    interventionSummary: "Auto summary for AI (intervention)",
    add: "+ Add",
    interventionNamePh: "Intervention name",
    minutesPh: "Time (min)",
    exerciseNamePh: "Exercise name",
    holdPh: "Hold (s)",
    modalityTargetPh: "Target area",
    educationPh: "Posture education, precautions, HEP, activity modification…",
    clinicalPlaceholder: "Enter detailed clinical reasoning…",
    analyze: "🚀 Generate AI clinical screening report",
    analyzing: "Scanning for red flags…",
    referralRequired: "Medical referral indicated",
    assessmentStatus: "Assessment status",
    referralPriority: "Evaluation paused (referral priority)",
    differentialTitle: "Clinical reasoning / differential",
    actionTitle: "Immediate action",
    actionDefault: "Defer physical therapy and prioritize appropriate medical referral.",
    dismissCase: "Finish referral workflow & screen new case",
    noRedFlagTitle: "No critical red flags detected",
    noRedFlagBody: "No clear medical emergency pattern was identified from the entered data.",
    verifyAgain: "Screen again",
    feedbackAccurate: "Accurate",
    feedbackFp: "False positive",
    feedbackFn: "False negative",
    notProvided: "Not documented",
    none: "None",
    prefixChief: "Chief complaint",
    prefixOnset: "Onset",
    prefixVas: "Pain (VAS)",
    prefixQuality: "Pain quality",
    prefixAgg: "Aggravating",
    prefixRelief: "Relieving",
    prefixRedFlag: "Red flags",
    prefixNotes: "Notes",
    redFlagNone: "None reported",
    tagTbc: "[TBC]",
    tagOutcome: "[Outcome measure]",
    tagIcfBf: "[ICF — body functions]",
    tagIcfAct: "[ICF — activity]",
    tagIcfPart: "[ICF — participation]",
    icfCatBody: "Body functions",
    icfCatActivity: "Activity limitations",
    icfCatParticipation: "Participation restrictions",
    weeks: "wk",
    analyzeError: "An error occurred during red flag analysis.",
    tryAgain: "Please try again shortly.",
    dbLogWarn: "Analysis completed but logging to the database failed.",
    tagEstimatedDuration: "[Estimated duration of care]",
    tagRomMmt: "[ROM/MMT]",
    manualSummaryNone: "- None",
    interventionMin: "min",
    interventionSec: "s",
    modalityTargetLabel: "Target:",
    tagBaselineVas: "[Baseline VAS]",
    tagDiagnosisRegion: "[Diagnosis region]",
    notSelected: "Not selected",
    tagIcfActivityLine: "[ICF — activity]",
    tagOutcomeLine: "[Outcome measure]",
    noData: "No data",
    loadVas: "Insert VAS",
    loadIcfActivity: "Insert ICF activity",
    loadOutcome: "Insert outcome score",
    loadRegion: "Insert diagnosis region",
    loadIcfParticipation: "Insert ICF participation",
    loadPrognosis: "Insert prognosis",
    modalBadge: "Step 2 · Outcome measure",
    modalTitleFallback: "Outcome measure",
    modalClose: "Close",
    modalError: "Unable to load this measure.",
    modalErrorHint: "Select a supported region (e.g., neck, shoulder, lumbar, or knee).",
    modalPreview: "Live result",
    modalSelectPrompt: "Please complete all items.",
    modalCancel: "Cancel",
    modalApply: "Apply score to chart",
    modalProgress: "Progress",
    modalItems: "items",
    scorePts: "pts",
    womacPain: "Pain",
    womacStiff: "Stiffness",
    womacFunc: "Physical function",
    womacSumLabel: "Pain + stiffness + function",
    dashReferralFallback: "Medical referral indicated",
    dashOverallScore: "Overall clinical reasoning score",
    dashLogicAudit: "Logic chain audit",
    dashCpgCompliance: "CPG compliance",
    dashAuditDefense: "Audit defense",
    dashTrajectory: "Predictive trajectory",
    dashDefenseScore: "Defense score",
    dashWeeksLabel: "wk est.",
    dashRedFlagNote: "Prioritize medical referral over prognosis interpretation when red flags are present.",
    dashRedFlagTitle: "Red Flag (critical risk signals)",
    dashRedFlagBody:
      "Critical medical risk signals were detected from the provided data. Prioritize medical triage and referral.",
    dashRedFlagBodyClear: "No critical Red Flag is detected at this time.",
    dashYellowFlagTitle: "Yellow Flag (psychosocial & chronicity risk factors)",
    dashYellowFlagBody: "Psychosocial caution factors identified from the input data will be shown here.",
    dashSaveRecord: "Save to Diagnosis Record",
    dashSaveRecordSaving: "Saving...",
    dashSaveRecordSaved: "The record was safely saved to the clinical timeline.",
    dashSaveRecordAlready: "The latest diagnosis record is already saved.",
    dashSaveRecordRetry: "Retry save",
    dashSaveRecordError: "An error occurred while saving.",
    dashInterventionStrategyTitle: "Intervention Strategy",
    dashProfessionalDiscussionTitle: "Professional Discussion",
    dashClinicalReasoningTitle: "Clinical Reasoning & Pathomechanics",
    dashCommunity: "Community & social sharing",
    dashChallenge: "🏆 Post challenge",
    dashDefenseShare: "🛡️ Share defense tip",
    dashInstagram: "📱 Branding card",
    dashDisclaimer:
      "This report is an AI-assisted mapping of input data to published guidelines. Diagnosis and treatment decisions must be made by a licensed clinician; this service assumes no liability for outcomes.",
    dashWaiting: "Awaiting AI analysis. Complete the form on the left and run analysis.",
    dashImprovement: "Improvement tip",
    shareFail: "Share failed",
    shareChallengeOk: "🏆 Challenge card posted to the community.",
    shareDefenseOk: "🛡️ Defense tip shared anonymously.",
    shareError: "Community upload error.",
  },
} as const;

export type SoapWizardCopy = (typeof COPY)["en"];

export function soapWizardCopy(locale: SoapLocale): SoapWizardCopy {
  return COPY[locale] as SoapWizardCopy;
}

/** Canonical exam values (storage) — labels from soapWizardCopy */
export const ONSET_OPTIONS = ["Acute", "Subacute", "Chronic"] as const;
export const TRAUMA_OPTIONS = ["Traumatic", "Non-traumatic"] as const;
export const PAIN_QUALITY_OPTIONS = ["Sharp", "Aching", "Burning", "Throbbing", "Tingling", "Dull"] as const;

export function onsetLabel(v: (typeof ONSET_OPTIONS)[number], locale: SoapLocale): string {
  if (locale === "en") return v;
  const m: Record<string, string> = { Acute: "급성 (Acute)", Subacute: "아급성 (Subacute)", Chronic: "만성 (Chronic)" };
  return m[v] ?? v;
}

export function traumaLabel(v: (typeof TRAUMA_OPTIONS)[number], locale: SoapLocale): string {
  if (locale === "en") return v;
  const m: Record<string, string> = { Traumatic: "외상성 (Traumatic)", "Non-traumatic": "비외상성 (Non-traumatic)" };
  return m[v] ?? v;
}

export function painQualityLabel(v: (typeof PAIN_QUALITY_OPTIONS)[number], locale: SoapLocale): string {
  if (locale === "en") return v;
  const m: Record<string, string> = {
    Sharp: "날카로운",
    Aching: "쑤시는",
    Burning: "타는듯한",
    Throbbing: "뻐근한",
    Tingling: "저리는",
    Dull: "묵직한",
  };
  return m[v] ?? v;
}

export const PROGNOSIS_WEEKS_KO = ["1주", "2주", "3주", "4주", "5주", "6주", "7주", "8주", "9주", "10주", "11주", "12주 이상"] as const;
export const PROGNOSIS_WEEKS_EN = [
  "1 wk",
  "2 wk",
  "3 wk",
  "4 wk",
  "5 wk",
  "6 wk",
  "7 wk",
  "8 wk",
  "9 wk",
  "10 wk",
  "11 wk",
  "12+ wk",
] as const;
